gmfe/react-gm

.gitignore
index.html
index.js
lib/animationicon.component.js
lib/react-gm.css

add svg animation icon

---

demo/component/layout.js
demo/component/overlay.js
doc/Loading.md
src/component/loading.js
src/css/loading.less
src/index.js
src/index.less

add componengt: Loading

---

demo/doc/SheetSelect.md
src/component/sheet.js

sheet select 增加isDisabled props

---

demo/doc/Trigger.md
src/component/trigger/index.js
src/component/trigger/style.less

pr: 添加浮层的三角标

---

demo/doc/Menu.md
demo/doc/nav.config.js
demo/route.js
src/component/menu/index.js
src/component/menu/style.less
src/index.js
src/index.less

1、增加导航菜单 Menu 组件

---

demo/doc/Menu.md
src/component/menu/index.js
src/component/menu/style.less

1、增加菜单点击后的样式
2、增加暴力提示，提示调用方使用组件时要用 key 标识组件

1、增加菜单点击后的样式

---

demo/doc/Menu.md
src/component/menu/index.js
src/component/menu/style.less

2、增加在当前菜单项时菜单的 title 的箭头模糊效果
3、修改菜单不可点击使鼠标为箭头而不是禁止符号

1、增加菜单可收起展开功能与否的字段

---

src/component/loading/style.less

optimize loading

---

src/component/tip/index.js
src/css/shadow.less
src/validator/rules.js

1、修复 eslint v4+ no-useless-escape  问题
2、优化 box-shadow 
3、删除 gm-box-shadow-modal 因为 modal 中使用到的 panel 选择器已经存在阴影

box-shadow optimize

---

src/component/input/input.number.js

inputNumber全选输入string bug

---

demo/doc/Radio.md
src/component/checkbox/checkbox.js
src/component/checkbox/checkbox_group.js
src/component/checkbox/style.less
src/component/radio/radio.js
src/component/radio/radio_group.js
src/component/radio/style.less

Feature radio style

---

demo/doc/DatePicker.md
demo/doc/DateRangePicker.md
src/component/datepicker/datepicker.js
src/component/datepicker/daterangepicker.js
src/component/datepicker/style.less

DatePicker和DateRangePicker都增加了清除所选时间功能：
对应的props是`canClear`

datepicker 增加清除所选时间选项

---

src/component/datepicker/datepicker.js
src/component/datepicker/daterangepicker.js
src/component/datepicker/style.less

datepicker ui fix

---

src/component/datepicker/datepicker.js
src/component/datepicker/daterangepicker.js

`className={canClear ? *** : ***}`
换成
`className={classNames(***,{"***": canClear})}`

use classNames

---

src/component/quick/index.js
src/index.less

修复gm-12  class

---

demo/app.js
demo/doc/Sheet.md
deploy/publish.sh
framework/top_content.js
package.json
src/css/border.less
src/css/display.less
src/css/distance.less
src/css/input.less
src/css/shadow.less
src/css/text.less

v6.1.0
废弃 publish.sh
topContent 增加 fixedTop
特定样式添加 !important
Sheet 补充demo

Feature someyouhua

---

README.dev.md
demo/app.js
demo/component/demo.js
demo/doc/Popover.md
demo/doc/nav.config.js
demo/index.less
demo/route.js
framework/style.less
package.json
src/component/dialog/index.js
src/component/layout_root/index.js
src/component/mask/index.js
src/component/mask/style.less
src/component/modal/index.js
src/component/popover/index.js
src/component/popover/popup.js
src/component/popover/style.less
src/component/trigger/index.js
src/index.js
src/index.less
src/var.less

引入 Popover ， 逐步废弃 Trigger。（Trigger是在target dom 同层级render的，不太合理。）
目前 接入了 framework 的可接入 Popover。

Feature Popover and 修正一些bug

---

src/component/collapse/index.js

Fix the warning of invalid type at Collapse component.

Fix the warning of Collapse component.

---

README.dev.md
demo/doc/Button.md
demo/doc/Loading.md
demo/doc/nav.config.js
demo/index.less
demo/route.js
package.json
src/component/button/index.js
src/component/button/style.less
src/component/filter_select/filter.select.js
src/component/filter_select/multiple.filter.select.js
src/component/layout_root/index.js
src/component/loading/index.js
src/component/loading/loading_chunk.js
src/component/loading/loading_full_screen.js
src/component/loading/style.less
src/emitter/index.js
src/index.js
src/index.less

1、增加封装了 loading 状态的 button
2、Loading 组件重构，增加了全屏加载 和 加载时的文案功能，兼容旧 Loading

1、增加封装了 loading 状态的 button

---

framework/breadcrumb.js
framework/framework.js
framework/style.less
package.json
src/emitter/index.js

framework 二期

---

package.json
src/component/calendar/index.js
src/component/dialog/index.js
src/component/drop_select/index.js
src/component/import_lead/index.js
src/component/pagination/pagination.js
src/component/pagination/pagination.text.js
src/component/pagination/pagination_box.js
src/component/pagination/pagination_new.js
src/component/quick/quick_detail.js
src/component/quick/quick_filter.js
src/component/quick/quick_panel.js
src/component/sheet/sheet.js
src/component/transfer/box.js
src/component/transfer/transfer.js
src/component/transfer/transfer_group.js
src/component/tree/index.js
src/component/tree_select/index.js
src/index.js
src/locales/index.js
src/locales/lng/en.json
src/locales/lng/index.js
src/locales/lng/zh.json
webpack.config.js

Feature gm i18n

---

demo/doc/Sheet.md
postcss.config.js
src/component/sheet/sheet.js
src/component/sheet/sheet_column.js
webpack.config.dll.js
webpack.config.js

@desc sheet 的 children 有可能是 false 等特殊值(和 Form 组件类似), 将其转化为数组的方式使用 React.Children.toArray 替换, 可以将特殊值替换掉;

@hotfix sheet 组件 children 解析问题及引入 SheetColumn 渲染方法的第三个参数 record(本行数据)

---

src/component/tree/index.js

tree 组件搜索时自动展开结果，transferGroup中用了 Tree

tree 组件搜索时自动展开结果

---

demo/doc/Pagination.md
src/component/pagination/style.less
src/index.less

PaginationBox添加disable反馈和文档

---

src/component/switch/index.js
src/component/switch/style.less

Switch组件优化

---

table/style.less

解决table滚动问题

---

demo/doc.nav.config.js
demo/doc/Price.md
src/component/price/index.js
src/index.js

对这个”Intl.NumberFormat“构造器类做了封装，兼容性在MDN上了解到是兼容到IE11。
该组件具备的特性：
具有可配置的货币符号；显示千分符；保留小数的精度；提供一个静态方法改变货币符号；样式默认上下文环境，可在style属性配置；接受传入以”分“为单位的价格；

Feature add price

---

src/component/modal/index.js
src/component/modal/style.less

modal-title

---

demo/doc/Progress.md
src/component/progress/index.js
src/component/progress/style.less

进度条内嵌文字支持固定位置

---

src/component/input_number/number.js
src/component/input_number/style.less
src/index.less

1. format code
2. hidden control button
3. rewrite unsafe lifecycle

improve inputnumberv2

---

demo/doc.nav.config.js
demo/doc/ClassName.md
demo/doc/Popover.md
demo/doc/Select.md
frame/framework.js
frame/mobile.less
package.json
src/component/list/style.less
src/component/popover/index.js
src/component/select/option.js
src/component/select/select.js
src/component/select/style.less
table/style.less

select 切 popover
补充 MoreSelect 入口
Table resize 调整
fix mobile full_tab leftWidth

Feature select

---

src/component/more_select/base.js

拼音过滤时，键盘操作的list非过滤后的list
多选时，enter不生效

fix moreselect

---

table/dnd_table.js

fix dnd table

---

src/component/nav/index.js
src/component/nav/nav.stories.js
src/component/nav/style.less

Feature 9.x

---

src/business/manage_pagination/stories.js
src/component/button/button.stories.js
src/less/buttons.less

remove the outline of the link button

change the link button styles

---

src/component/filter_select/style.less
src/component/transfer/box.js
src/component/transfer/transfer.js

1. transfer组件增加disabled
2. MultipleFilterSelect组件disabled状态时，背景置灰

transfer增加disabled

---

src/component/steps/index.js
src/component/steps/steps.stories.js
src/component/steps/style.less
src/index.js
src/index.less

static steps
